---
- hosts: webservers
  become: true
  tasks:
    - name: Stop Nginx service
      service:
        name: nginx
        state: stopped
      notify: Run certbot

    - name: Run certbot command to obtain SSL certificate
      shell: |
        certbot certonly --standalone -d uat-cms.paar.org.in --register-unsafely-without-email
      args:
        executable: /bin/bash
      notify: Start Nginx

    - name: Start Nginx service
      service:
        name: nginx
        state: started

  handlers:
    - name: Run certbot
      meta: noop
      notify: Run certbot

    - name: Start Nginx
      service:
        name: nginx
        state: started
