- hosts: webservers
  become: true
  tasks:
    - name: Run npm install in /opt/PAAR/paar-backend
      shell: . ~/.nvm/nvm.sh && ~/.nvm/versions/node/v16.13.2/bin/npm install --force
      args:
        chdir: /opt/PAAR/paar-backend
